### ISSUE TITLE
Fails is there are no acq, run, or dir entities in the dwi file. 

### ISSUE THREAD

**Issue by akhanf** [akhanf/snakedwi#57]
The workflow currently uses the presence of acq/run/dir entities to represent dwi files before merging, and the merged file without any of these entities. So there is currently a bug if the input dwi file has none of these entities defined. 

One fix could be to add a entity (e.g. desc-raw) to the input dwi files upon import into the workflow. Or, could add an entity to the merged dwi file (e.g. desc-merged).

**Comment by akhanf** [comment]
btw the bug manifests itself as this error: 
```
Building DAG of jobs...
AmbiguousRuleException:
Rules concat_runs_bvec and dwidenoise are ambiguous for the file work/sub-BCT1003/dwi/sub-BCT1003_desc-denoise_dwi.bvec.
Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
Wildcards:
    concat_runs_bvec: desc=denoise,subject=BCT1003
    dwidenoise: subject=BCT1003
Expected input files:
    concat_runs_bvec: snakedwi/sub-BCT1003/dwi/sub-BCT1003_workflowopts
    dwidenoise: work/sub-BCT1003/dwi/sub-BCT1003_dwi.nii.gz work/sub-BCT1003/dwi/sub-BCT1003_dwi.bvec work/sub-BCT1003/dwi/sub-BCT1003_dwi.bval work/sub-BCT1003/dwi/sub-BCT1003_dwi.jsonExpected output files:
    concat_runs_bvec: work/sub-BCT1003/dwi/sub-BCT1003_desc-denoise_dwi.bvec
    dwidenoise: work/sub-BCT1003/dwi/sub-BCT1003_desc-denoise_dwi.nii.gz work/sub-BCT1003/dwi/sub-BCT1003_desc-denoise_dwi.bvec work/sub-BCT1003/dwi/sub-BCT1003_desc-denoise_dwi.bval work/sub-BCT1003/dwi/sub-BCT1003_desc-denoise_dwi.json
```
